language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: 
  - gem install jekyll
  - gem install jekyll-paginate
script: 
  - jekyll build
  - bundle exec rake
  - npm run ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master

