# Site settings
title: 柏梓涵的官方网站
SEOTitle: 柏梓涵的官方网站
header-img: img/home-bg-n.jpg
email: bai5775@outlook.com
description: "关于我与世界 | 柏梓涵，Software Engineer，UX Designer | 这里是 @柏梓涵 的个人网站，与你一起发现更大的世界。"
keyword: "柏梓涵, BerBai, 柏战不殆, 博客, 个人网站, 互联网, 深度学习, 全栈, 设计"
url: "https://smartBBer.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/smartBBer/smartbber.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "越努力，越幸运<br>纵力量绵薄，也要筑起通往梦想的桥梁。"
sidebar-avatar: /img/avatar-bb-portray.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     smartBBer
zhihu_username:     da-lang-bei
github_username:    smartBBer
facebook_username:  bai5775
jianshu_username:   a20ad796d7a3
#twitter_username:   username




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: smartBBer

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1ba8f62d66228ee3f6f6                            #生成的clientID
  clientSecret: e1d80d348dd24efba227a98a87c9c61820e807a3    #生成的clientSecret
  repo: smartBBer.github.io    #仓库名称
  owner: smartBBer    #github用户名
  admin: smartBBer
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: becddaef61a08850869c1e21a2a071d4

# Google Analytics
ga_track_id: 'UA-125101386-1'            # Format: UA-xxxxxx-xx
ga_domain: smartbber.github.io              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    #},{
    #    title: "前端外刊评论",
    #    href: "http://qianduan.guru/"
    #},{
    #    title: "天镶的博客",
    #    href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    #},{
    #    title: "解旻的博客",
    #    href: "http://xieminis.me/"
    }
]
